// <auto-generated />
using System;
using AppSec.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OdeToFood.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180913190235_Nowe")]
    partial class Nowe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

               
            modelBuilder.Entity("OdeToFood.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("ReviewId");

                    b.Property<int>("Stars");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("UserId");

                    b.Property<string>("restaurantId");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

          
#pragma warning restore 612, 618
        }
    }
}
